### PR TITLE
Process 'copyGroups' attribute

### PR DESCRIPTION
**Pull request by miguelsousa**
Relates to https://github.com/adobe-type-tools/afdko/issues/753

### CODE REVIEW

**Comment by miguelsousa** [comment]
It just occurred to me that this process of copying the groups should probably take `kerningGroupConversionRenameMaps` into account. Otherwise the resulting instance may end up with duplicate kerning groups, e.g. **@MMK_L_LAT_A** and **public.kern1.LAT_A** in the same `groups.plist` file.

@LettError WDYT?

**Comment by LettError** [comment]
Err, are you using UFO2? Do you have a small test maybe?

**Comment by typemytype** [comment]
in a UFO3 world `@MMK_L_LAT_A` is not a valid kerning group, it will be converted with a kerning prefix, and the old group name is removed. 

see https://github.com/fonttools/fonttools/blob/master/Lib/fontTools/ufoLib/converters.py#L27-L32

**Comment by miguelsousa** [comment]
@typemytype I understand that. The case I'm thinking about is:
* masters have kerning and are UFO2
* instance has kerning and is UFO3

If the copyGroups step blindly copies all the groups from the default master into the instance, the latter will have duplicate data, I think.

@LettError working on crafting a test

**Comment by typemytype** [comment]
internally all current tools always up-convert to UFO3 inside

if a script/user wants to save as UFO2, which that is possible, then in your example the instance  will have kerning group with UFO3 style group naming, that is not bad. 

The only reason why a rename back to MM names is nice, is if you want to edit kerning of that UFO file in MM afterwards...

**Comment by miguelsousa** [comment]
I'm fine with ending up with a UFO2 that has `public.kern` prefixes. What I'm trying to avoid is a UFO3 that contains both sets (MM and public.kern). Judging from the tests I've ran so far, the current code saves UFO3 instances with both sets.

**Comment by frankrolf** [comment]
This issue comes from my workshop files, which were translated from UFO2 to UFO3 in Robofont. It’s possible that old-school kerning groups did stick around in them.

If I can help with any kind of test scenario I’d be glad to – please let me know which kinds of files would be needed.

**Comment by LettError** [comment]
Can you send me those files, and a designspace maybe?

**Comment by miguelsousa** [comment]
The FDK's test files can be found here https://github.com/adobe-type-tools/afdko/tree/develop/tests/makeinstancesufo_data/input

**Comment by frankrolf** [comment]
Attached here. The input masters are UFO3 files, with `kern.X` groups in them. Additionally, they have a non-kerning related group `COMBINING_MARKS` group, which goes missing in the instances. The `COMBINING_MARKS` group is the same across masters. 
The loss of this group is independent of a `<groups copy="1" />` flag in the designspace file.

[Masters.zip](https://github.com/LettError/ufoProcessor/files/2943715/Masters.zip)

**Comment by LettError** [comment]
The groups are copied from the default when kerning is calculated. So the copyGroups flag is not really flagging very much any more.

* Is there a use case in which the kerning + groups come from the default, but non-kerning groups come from elsewhere?

Otherwise it might be easier to just accept all groups from the default.

**Comment by miguelsousa** [comment]
With the latest changes I think things are working as expected.
@frankrolf can you test with afdko 2.8.7?

**Pull request merged**
