### PR TITLE
Fix anchors

### LINKED ISSUE #26: Swapping glyphs deletes anchors
1. ufoProcess [SwapGlyphNames.zip](https://github.com/LettError/ufoProcessor/files/4129654/SwapGlyphNames.zip)
2. Compare anchors of `a` and `a.swap` in C.ufo and D.ufo

Cosimo fixed this for fontmake over at https://github.com/googlefonts/fontmake/pull/632.

### PR DESCRIPTION
**Pull request by benkiel**
This closes #26, and would fix the issue over at Recursive (https://github.com/arrowtype/recursive/issues/448)

### CODE REVIEW

**Comment by benkiel** [comment]
With a test even!

**Comment by colinmford** [comment]
I just noticed I was having this particular issue yesterday, and here we are, @benkiel has already fixed it. Thanks, @benkiel!

**Comment by benkiel** [comment]
@colinmford you can pull from my fork for now, until this is merged, that's what @arrowtype did for Recursive

**Comment by colinmford** [comment]
@benkiel thanks that's a good idea

**Comment by colinmford** [comment]
🙏 @LettError thanks for the merge!

**Comment by arrowtype** [comment]
Thank you, @benkiel and @LettError!

**Comment by LettError** [comment]
Sorry for the delay.

**Pull request merged**
